version: '3.8'

services:
  ai_engine:
    build: ./ai_engine
    container_name: sensemesh-ai
    ports:
      - "7860:7860"
    restart: always

  server:
    build: ./server
    container_name: sensemesh-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AI_SERVICE_URL=http://ai_engine:7860
    depends_on:
      - ai_engine

  client:
    build: ./client
    container_name: sensemesh-client
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - server
